language: php

php:
  - '7.2'
  - '7.3'

install:
  travis_retry composer install --dev --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
